version: '3.8'

services:
  postgres:
    container_name: skimart-postgres-db
    hostname: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: faroc
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: skimart-redis
    volumes:
      - redis_conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"

volumes:
  redis_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/dockerVolumes/skimart/redis/conf